### ISSUE TITLE
Fix Resume Download Formatting Issues

### ISSUE THREAD

**Issue by riteshpalya** [riteshpalya/quickresumebuilder#2]
When downloading a resume from the website, the following issues occur:

- The colors on the resume are disabled or do not match the original design.
- Text formatting changes, including font styles and alignment, are altered in the downloaded version.
- The resume is not formatted to A4 size, making it difficult for printing and proper display.

*Expected Outcome*:  
The downloaded resume should retain the original colors, text formatting, and be in A4 size for consistent display and printing.

**Comment by Mayuphapale** [comment]
I would like to work on this issue . Can you please assign this issue to me ?
